<?php

namespace App\Http\Requests\API\Client\Services;

use App\Http\Requests\API\BaseRequest;

class ClientRateServicesRequestsRequest extends BaseRequest
{


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'client_service_request_id' => 'required|numeric|exists:client_requests,id',
            'rate' => 'required|numeric|in:0,1,2,3,4,5',
            'comment' => 'sometimes',
        ];
    }

    public function messages()
    {
        return [
            'client_advisory_services_reservation_id.required' => 'يجب ادخال رقم الحجز ',
            'client_advisory_services_reservation_id.numeric' => 'يجب ادخال رقم الحجز بالارقام فقط',
            'client_advisory_services_reservation_id.exists' => '  رقم الحجز غير موجود',
            'rate.required' => ' يجب ادخال التقييم',
            'rate.numeric' => ' يجب ادخال التقييم بشكل صحيح',
            'rate.in' => ' يجب ادخال التقييم بشكل صحيح داخل خيارات 0,1,2,3,4,5',

        ]; // TODO: Change the autogenerated stub
    }
}
