<?php

namespace App\Http\Requests\API\Client\Lawyer\Rate;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class ClientCreateLawyerRateRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'lawyer_id' => 'required|string|exists:lawyers,id',
            'rate' => 'required|numeric|in:0,1,2,3,4',
            'comment' => 'sometimes'
        ];
    }
    public function messages()
    {
        return [
            'lawyer_id.required' => 'يجب اختيار مقدم خدمة ',
            'lawyer_id.numeric' => 'يجب اختيار مقدم خدمة صحيح ',
            'lawyer_id.exists' => '  مقدم خدمة غير موجود ',
            'rate.required' => 'يجب ادخال تقييم ',
            'rate.numeric' => 'يجب ادخال تقييم بشكل صحيح ',
            'rate.in' => ' يجب ادخال تقييم صحيح يكون بين 0,1,2,3,4 ',
        ]; // TODO: Change the autogenerated stub
    }
}
