<?php

namespace App\Http\Requests\API\Client\Book;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class addBookRateRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'book_id' => 'required|numeric|exists:books,id',
            'rate' => 'required|numeric|in:0,1,2,3,4',
            'comment' => 'sometimes',
        ];
    }

    public function messages()
    {
        return [
            'book_id.required'=>'يجب اختيار كتاب',
            'book_id.numeric'=>'يجب اختيار كتاب بشكل صحيح ',
            'book_id.exists'=>'الكتاب غير موجود',

            'rate.required'=>'يجب  كتابة تقييم',
            'rate.numeric'=>'يجب كتابة التقييم بشكل صحيح ',
            'rate.in'=>'التقييم يجب ان يكون ضمن 0,1,2,3,4',
        ]; // TODO: Change the autogenerated stub
    }
}
