<?php

namespace App\Http\Requests\API\Client\FavoritesLawyers;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class ClientAddFavoritesLawyersRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'lawyer_id' => 'required|string|exists:lawyers,id'
        ];
    }
    public function messages()
    {
        return [

        ]; // TODO: Change the autogenerated stub
    }
}
