<?php

namespace App\Http\Requests\API\Lawyer\Auth\Login;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class LawyerLoginRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'credential1'=>'required',
            'password'=>'required',

        ];
    }
    public function messages()
    {
        return [
            'credential1.required'=>'حقل الموبايل او البريد الاكتروني مطلوب',
            'password.required'=>'حقل كلمة المرور مطلوب',

        ]; // TODO: Change the autogenerated stub
    }
}
