<?php

namespace App\Http\Requests\API\Lawyer\ContactYmtaz;

use App\Http\Requests\API\BaseRequest;

class LawyerSaveContactMessageRequest extends BaseRequest
{


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'subject'=>'required',
            'details'=>'required',
            'file'=>'sometimes|mimes:png,jpg,jpeg,PNG,JPG,JPEG',
        ];
    }
    public function messages()
    {
        return [
            'subject.required'=>'حقل عنوان الرسالة مطلوب',
            'details.required'=>'حقل محتوى الرسالة مطلوب',
        ]; // TODO: Change the autogenerated stub
    }
}
