<?php

namespace App\Http\Requests\API\Client\Profile;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ClientUpdateProfileImageRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'image'=>'required|mimes:png,jpg,jpeg,PNG,JPG,JPEG|max:8140'
        ];
    }

    public function messages()
    {
        return [
            'image.required'=>'يجب اختيار صورة ',
            'image.mimes'=>' png,jpg,jpeg,PNG,JPG,JPEG يجب ان تكون صيغة الصورة '

        ]; // TODO: Change the autogenerated stub
    }
}
