<?php

namespace App\Http\Requests\API\Client\Auth\Password;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class ClientResetPasswordRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'code' => 'required|numeric|exists:service_users,pass_code',
            'password' => 'required|confirmed',
        ];
    }

    public function messages()
    {
        return [
            'code.required' => 'حقل كود التحقق مطلوب',
            'password.required' => 'حقل كلمة المرور مطلوب',
            'code.numeric' => 'حقل كود التحقق يجب ان يكون ارقام',
            'code.exists' => 'حقل كود التحقق غير موجود',

        ]; // TODO: Change the autogenerated stub
    }
}
