<?php

namespace App\Http\Requests\API\Client\Auth\Password;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class ClientPostForgotPasswordRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        $type = request()->type ;
        return [
            'type'=>'required|numeric|in:1,2',
            'credential'=>$type == 1 ?'required|email|exists:service_users,email':'required|numeric|exists:service_users,mobil',

        ];
    }
    public function messages()
    {
        return [
            'email.required'=>'حقل البريد الاكتروني مطلوب',
            'email.email'=>'حقل البريد الاكتروني يجب ان يكون بشكل صحيح',
            'email.exists'=>'حقل البريد الاكتروني غير موجود',

        ]; // TODO: Change the autogenerated stub
    }
}
