<?php

namespace App\Http\Requests\API\Client\Auth\Register;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class ClientActivateAccountRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'client_id' => 'required|string|exists:service_users,id',
            'otp_code' => 'required|numeric|exists:service_users,active_otp',
        ];
    }
    public function messages()
    {
        return [
            'client_id.required' => ' مطلوب  client_id حقل ',
            'client_id.exists' => 'غير صحيح client_id  حقل',

            'otp_code.required' => 'مطلوب ادخال رمز التحقق المرسل لكم',
            'otp_code.numeric' => 'رمز التحقق يجب ان يكون مكون من ارقام فقط',
            'otp_code.exists' => 'رمز التحقق غير موجود',
        ]; // TODO: Change the autogenerated stub
    }
}
