<?php

namespace App\Http\Requests\API\Merged;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class AccountLoginRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'email' => 'required',
            'password' => 'required',

        ];
    }
    public function messages()
    {
        return [
            'email.required' => 'حقل البريد الاكتروني مطلوب',
            'password.required' => 'حقل كلمة المرور مطلوب',

        ]; // TODO: Change the autogenerated stub
    }
}
