<?php

namespace App\Http\Requests\API\Merged;

use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class CreateContactUsRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        $rules = [
            "subject" => 'required',
            'details' => 'required',
            'type' => 'required|in:1,2,3',
            "file" => "sometimes",
            'email' => "sometimes|email",
            "name" => "sometimes"
        ];

        if (!Auth::guard("api_account")->check()) {
            $rules['email'] = 'required|email';
            $rules['name'] = 'required';
        }

        return $rules;
    }

    public function messages()
    {
        return [
            "*.required" => "الحقل مطلوب",
            "*.in" => "يجب ان يكون ال نوع 1 او 2 او 3",
            "email.email" => "البريد الالكتروني غير صحيح",
        ]; // TODO: Change the autogenerated stub
    }
}
