<?php

namespace App\Http\Requests\API\Lawyer\LawyerAdvisoryService;

use App\Http\Requests\API\BaseRequest;

class LawyerCreateAdvisoryServiceReservationRequest extends BaseRequest
{


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'advisory_services_id' => 'required|numeric|exists:advisory_services,id',
            'type_id' => 'required|numeric|exists:advisory_services_types,id',
            'description' => 'required',
            'accept_rules' => 'required||numeric|in:1',
            'file' => 'sometimes|mimes:png,jpg,jpeg,PNG,JPG,JPEG,pdf,PDF',
        ];
    }

    public function messages()
    {
        return [
            'advisory_services_id.required' => 'يجب اختيار استشارة',
            'advisory_services_id.numeric' => ' الاستشارة يجب ان يكون ارقام',
            'advisory_services_id.exists' => ' الاستشارة غير موجودة',

            'type_id.required' => 'يجب اختيار نوع استشارة',
            'type_id.numeric' => 'نوع الاستشارة يجب ان يكون ارقام',
            'type_id.exists' => ' نوع الاستشارة غير موجود',

            'content.exists' => ' محتوى الاستشارة  مطلوب',
            'accept_rules.in' => ' يجب الموافقة على السياسات والشروط',

            'file.mimes' => 'png,jpg,jpeg,PNG,JPG,JPEG,pdf,PDF الملف يجب ان يكون بصيغة ',
        ]; // TODO: Change the autogenerated stub
    }
}
