<?php

namespace App\Http\Requests\API\Lawyer\LawyerAdvisoryService;

use App\Http\Requests\API\BaseRequest;

class LawyerDelayAppointmentAdvisoryServiceReservationRequest extends BaseRequest
{


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'appointment_id' => 'required|numeric|exists:lawyer_advisory_services_reservation_appointment,id',
            'date_id' => 'required|numeric|exists:advisory_services_available_dates,id',
            'time_id' => 'required|numeric|exists:advisory_services_available_dates_times,id',
        ];
    }

    public function messages()
    {
        return [
            'day.required' => 'حقل اليوم مطلوب',
            'day.numeric' => 'حقل اليوم يجب ان يكون ارقام فقط',
            'month.required' => 'حقل الشهر مطلوب',
            'month.numeric' => 'حقل الشهر يجب ان يكون ارقام فقط',
            'year.required' => 'حقل السنة مطلوب',
            'year.numeric' => 'حقل السنة يجب ان يكون ارقام فقط',
            'time_clock.required' => 'حقل الساعة مطلوب',
            'time_clock.numeric' => 'حقل الساعة يجب ان يكون ارقام فقط',
            'time_minute.required' => 'حقل الدقائق مطلوب',
            'time_minute.numeric' => 'حقل الدقائق يجب ان يكون ارقام فقط',
        ]; // TODO: Change the autogenerated stub
    }
}
