<?php

namespace App\Http\Requests\API\Lawyer\LawyerAdvisoryService;

use App\Http\Requests\API\BaseRequest;

class LawyerCancelAppointmentAdvisoryServiceReservationRequest extends BaseRequest
{


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'reservation_id' => 'required|numeric|exists:lawyer_advisory_services_reservations,id',
        ];
    }

    public function messages()
    {
        return [
            'reservation_id.required' => 'يجب ادخال رقم الحجز',
            'reservation_id.numeric' => 'يجب ادخال رقم الحجز بالارقام فقط',
            'reservation_id.exists' => ' رقم الحجز غير موجود',
        ]; // TODO: Change the autogenerated stub
    }
}
