<?php

namespace App\Http\Requests\Site\Lawyer\OrganizationRequests;

use Illuminate\Foundation\Http\FormRequest;

class OrganizationRequestsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            '*'=>'required',
            'file'=>'sometimes'
        ];
    }
    public function messages()
    {
        return [
            '*.required'=>'الحقل مطلوب',
            'file.sometimes'=>'الحقل مطلوب',
        ]; // TODO: Change the autogenerated stub
    }
}
