<?php

namespace App\Http\Requests\Admin\Client;

use App\Models\Account;
use App\Models\Lawyer\Lawyer;
use App\Models\Country\Country;
use Illuminate\Validation\Rule;
use App\Models\Service\ServiceUser;
use Illuminate\Foundation\Http\FormRequest;

class ClientAdminUpdateProfileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        $request = request()->all();
        $u_id = request()->get('id');
        $phone_code = request()->get('phone_code');
        $country = Country::where('id', $request['country_id'])->first();
        $check_required = 'sometimes';
        if ($phone_code == 966) {
            $check_required = 'required_if:accepted,2';
        }


        return [
            'name' => 'required_if:accepted,2',
            'gender' => 'required_if:accepted,2',
            'type' => 'required_if:accepted,2',
            'phone_code' => 'required_if:accepted,2',
            'email' => [
                'required',
                'email',
                function ($attribute, $value, $fail) use ($u_id) {
                    // Rule::unique('lawyers', 'email')->ignore($u_id)->whereNull('deleted_at')
                    $accountExists = Account::where('email', $value)->whereNull('deleted_at')->where('id', '!=', $u_id)->exists();

                    if ($accountExists) {
                        $fail('البريد الإلكتروني موجود مسبقا');
                    }
                }
            ],
            'phone' => [
                'required_if:accepted,2',
                function ($attribute, $value, $fail) use ($u_id, $phone_code) {
                    $clientExists = Account::where('phone', $value)->where('phone_code', $phone_code)->whereNull('deleted_at')->where('id', '!=', $u_id)->exists();

                    if ($clientExists) {
                        $fail('هذا الرقم موجود مسبقا');
                    }
                }
            ],
            'country_id' => 'required_if:accepted,2',
            'region_id' => $check_required,
            'city_id' => $check_required,
            'longitude' => 'sometimes',
            'latitude' => 'sometimes',
            'nationality_id' => 'sometimes',
            'password' => 'sometimes',
            'status' => 'required',
            'status_reason' => 'sometimes'
        ];
    }

    public function messages()
    {
        return [
            'name.required_if' => 'الاسم مطلوب',
            'gender.required_if' => 'الجنس مطلوب',
            'type.required_if' => 'حقل الصفة مطلوب',
            'phone_code.required_if' => 'الحقل مقدمة الدولة مطلوب',
            'region.required_if' => 'حقل المنطقة مطلوب',
            'city.required_if' => 'حقل المدينة مطلوب',

            'longitude.required_if' => 'الحقل مطلوب',
            'latitude.required_if' => 'الحقل مطلوب',
            'password.required_if' => 'الحقل مطلوب',

            'email.required_if' => 'الحقل الايميل مطلوب ',
            'email.email' => 'يرجى ادخال ايميل صحيح   ',
            'email.unique' => 'الايميل موجود بالفعل ',

            'phone.required_if' => 'الحقل رقم الجوال مطلوب ',
            'phone.numeric' => 'يرجى ادخال رقم جوال صحيح   ',
            'phone.unique' => 'رقم الجوال موجود بالفعل ',
            'phone.digits' => 'يجب اراجعة خانات رقم الجوال ',
        ]; // TODO: Change the autogenerated stub
    }
}
