<?php

namespace App\Http\Requests\API\Client\Reservations;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ClientCreateReservationRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'day' => 'required|numeric',
            'month' => 'required|numeric',
            'year' => 'required|numeric',
            'time_clock' => 'required|numeric',
            'time_minute' => 'required|numeric',
            'type' => 'required|numeric|exists:client_reservations_types,id',
            'importance' => 'required|numeric|exists:client_reservations_importance,id',
            'notes' => 'sometimes'
        ];
    }

    public function messages()
    {
        return [
            'day.required' => 'حقل اليوم مطلوب',
            'day.numeric' => 'حقل اليوم يجب ان يكون ارقام فقط',
            'month.required' => 'حقل الشهر مطلوب',
            'month.numeric' => 'حقل الشهر يجب ان يكون ارقام فقط',
            'year.required' => 'حقل السنة مطلوب',
            'year.numeric' => 'حقل السنة يجب ان يكون ارقام فقط',
            'time_clock.required' => 'حقل الساعة مطلوب',
            'time_clock.numeric' => 'حقل الساعة يجب ان يكون ارقام فقط',
            'time_minute.required' => 'حقل الدقائق مطلوب',
            'time_minute.numeric' => 'حقل الدقائق يجب ان يكون ارقام فقط',
            'type.required' => 'حقل نوع الموعد مطلوب',
            'type.numeric' => 'حقل نوع الموعد يجب ان يكون ارقام فقط',
            'type.exists' => 'حقل نوع الموعد غير صحيح',
            'importance.required' => 'حقل درجة الاهمية مطلوب',
            'importance.numeric' => 'حقل درجة الاهمية يجب ان يكون ارقام فقط',
            'importance.exists' => 'حقل درجة الاهمية غير صحيح',

        ]; // TODO: Change the autogenerated stub
    }
}
