<?php

namespace App\Http\Requests\Site\Client\Auth;

use App\Models\Country\Country;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ClientAuthRegisterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        $request = request()->all();
        $country = Country::where('id', $request['country_id'])->first();
        $check_required = 'sometimes';
        $check_digits =  'digits:10';
        if ($country->phone_code == 966) {
            $check_required = 'required';
        }
        if ($request['phone_code'] == 966) {
            $check_digits = 'digits:9';

        }

        return [
            'name' => 'required',
            'gender' => 'required',
            'type' => 'required',
            'phone_code' => 'required',
            'mobile' => ['required',$check_digits, 'numeric', Rule::unique('service_users', 'mobil')->whereNull('deleted_at'), Rule::unique('lawyers', 'phone')->whereNull('deleted_at')],
            'email' => ['required', 'email', Rule::unique('service_users', 'email')->whereNull('deleted_at'), Rule::unique('lawyers', 'email')->whereNull('deleted_at')],
            'country_id' => 'required',
            'region_id' => $check_required,
            'city' => $check_required,
            'longitude' => 'sometimes',
            'latitude' => 'sometimes',
            'nationality_id' => 'sometimes',
            'password' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'name.required' => 'الاسم مطلوب',
            'gender.required' => 'الجنس مطلوب',
            'type.required' => 'الحقل مطلوب',
            'phone_code.required' => 'الحقل مطلوب',
            'region_id.required' => 'الحقل مطلوب',
            'city_id.required' => 'الحقل مطلوب',
            'longitude.required' => 'الحقل مطلوب',
            'latitude.required' => 'الحقل مطلوب',
            'password.required' => 'الحقل مطلوب',

            'email.required' => 'الحقل مطلوب ',
            'email.email' => 'يرجى ادخال ايميل صحيح   ',
            'email.unique' => 'الايميل موجود بالفعل ',

            'mobile.required' => 'الحقل مطلوب ',
            'mobile.numeric' => 'يرجى ادخال رقم جوال صحيح   ',
            'mobile.unique' => 'رقم الجوال موجود بالفعل ',
            'mobile.digits' => 'يجب اراجعة خانات رقم الجوال ',
        ]; // TODO: Change the autogenerated stub
    }
}
