<?php

namespace App\Http\Requests\API\Lawyer\Auth\Password;

use App\Http\Requests\API\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class LawyerForgotPasswordVerificationRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'code' => 'required|numeric|exists:lawyers,pass_code',

        ];
    }

    public function messages()
    {
        return [
            'code.required' => 'حقل كود التحقق مطلوب',
            'code.numeric' => 'حقل كود التحقق يجب ان يكون ارقام',
            'code.exists' => 'حقل كود التحقق غير صالح',

        ]; // TODO: Change the autogenerated stub
    }
}
