name: Development Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo_mysql, bcmath, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --no-dev

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - run: npm ci
      - run: npm run build

      - name: Build Docker image
        run: docker build -t chosey/ymtaz-laravel-development:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to DockerHub
        run: docker push chosey/ymtaz-laravel-development:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ymtaz.sa >> ~/.ssh/known_hosts

      - name: Run migrations on the server
        run: |
          ssh -i ~/.ssh/id_rsa root@ymtaz.sa <<EOF
          docker pull chosey/ymtaz-laravel-development:latest
          docker-compose -f /root/docker-compose.yml stop ymtaz-laravel-development
          docker-compose -f /root/docker-compose.yml rm -f ymtaz-laravel-development
          docker-compose -f /root/docker-compose.yml up -d ymtaz-laravel-development
          EOF
